version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web


  database:
    image: postgres:11
    env_file:
      - .env/development/database
